CREATE TABLE IF NOT EXISTS Categories(
	id BIGSERIAL PRIMARY KEY,
	nome VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Products(
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	nome VARCHAR(200) NOT NULL,
	price DECIMAL(8,2) NOT NULL,
	category_id INTEGER,
	FOREIGN KEY (category_id) REFERENCES Categories (id) ON DELETE SET NULL 
);